services:

  fastapi:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PIP_DEFAULT_TIMEOUT=100
      - DATABASE=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    env_file:
      - ./.env
    ports:
      - '8001:8001'
    volumes:
      - ./app:/project_fastapi/app
      - ./alembic:/project_fastapi/alembic
      - ./alembic.ini:/project_fastapi/alembic.ini
      - ./tests:/project_fastapi/tests
      - ${HOME}/.aws:/home/user/.aws:ro
      - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
      - ${HOME}/.ssh:/home/user/.ssh:ro
    depends_on:
      - db
    networks:
      - local

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c log_statement=all
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - local

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5001:80"
    networks:
      - local
    restart: unless-stopped

volumes:
  dev-db-data:
  pgadmin:

networks:
  local:
    driver: bridge
